ALTER TYPE "SubmissionStatus" ADD VALUE IF NOT EXISTS 'MEMORY_LIMIT_EXCEEDED';
ALTER TYPE "SubmissionStatus" ADD VALUE IF NOT EXISTS 'COMPILATION_ERROR';

ALTER TABLE "Problem" ADD COLUMN IF NOT EXISTS "timeLimitMs" INTEGER NOT NULL DEFAULT 1000;
ALTER TABLE "Problem" ADD COLUMN IF NOT EXISTS "memoryLimitMb" INTEGER NOT NULL DEFAULT 256;

ALTER TABLE "Submission" ADD COLUMN IF NOT EXISTS "compilerOutput" TEXT;
ALTER TABLE "Submission" ADD COLUMN IF NOT EXISTS "runtimeOutput" TEXT;
ALTER TABLE "Submission" ADD COLUMN IF NOT EXISTS "passedTestCases" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Submission" ADD COLUMN IF NOT EXISTS "totalTestCases" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Submission" ADD COLUMN IF NOT EXISTS "executionTimeMs" INTEGER;
ALTER TABLE "Submission" ADD COLUMN IF NOT EXISTS "memoryUsedKb" INTEGER;
ALTER TABLE "Submission" ADD COLUMN IF NOT EXISTS "failureTestCaseIndex" INTEGER;
ALTER TABLE "Submission" ADD COLUMN IF NOT EXISTS "judgedAt" TIMESTAMP(3);
