ALTER TABLE "Problem" ALTER COLUMN "difficulty" TYPE TEXT USING "difficulty"::text;

ALTER TABLE "Problem" ADD COLUMN IF NOT EXISTS "rating" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Problem" ADD COLUMN IF NOT EXISTS "tags" JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE "Problem" ADD COLUMN IF NOT EXISTS "inputFormat" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Problem" ADD COLUMN IF NOT EXISTS "outputFormat" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Problem" ADD COLUMN IF NOT EXISTS "publicTestCases" JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE "Problem" ADD COLUMN IF NOT EXISTS "hiddenTestCases" JSONB NOT NULL DEFAULT '[]'::jsonb;
